### ISSUE TITLE
Multiple Staff Page enhancements

### ISSUE THREAD

**Issue by sidpagariya** [KAMSC/kamsc.github.io#14]
Add multiple Staff Page enhancements as mentioned by Mr. Sinclair:
- [x] Profile picture
- [x] Courses Links
- [x] Load PDFs of problem sets, pictures, etc.
- [x] calendar items
- [x] assignments.

**Comment by rkalnins** [comment]
Sounds exciting!  I'll get working when I have time.

**Comment by sidpagariya** [comment]
I have already started work and will be done soon. It's all good, bro. I got this.
