### ISSUE TITLE
Completely changing the theme of this website

### ISSUE THREAD

**Issue by sidpagariya** [KAMSC/kamsc.github.io#4]
Since we have tons more pages on this website, I am thinking of completely changing the menu. But, to change the menu, we will have to make major changes to the entire website layout...
Any suggestions?
I will get the other website ready by tonigh

**Comment by rkalnins** [comment]
I'm thinking something clean and modern but most importantly the menus have to be accessible everywhere. Drop-down menus would be great.  I liked the style and layout we had with big images and text but if the scrolling could be reduced, that would be nice.  Have the important info very condensed at the top and then link to parts of the page down below.  You're just going to create a new branch right?

**Comment by rkalnins** [comment]
It would be best if it was responsive and fast (both in website design and finding information).  If I was a parent looking for information I'd like everything to be easily accessible and easy to find.  Therefore, the quick links were a temporary solution but changing the whole layout solves all of the smaller problems we would have down the line.

**Comment by rkalnins** [comment]
And once the new page is set up, transferring information and setting up the smaller features wouldn't be that hard.

**Comment by sidpagariya** [comment]
Still deciding on what kinda layout would be great...

**Comment by rkalnins** [comment]
I really liked the one we had just before but it just wasn't going to meet our needs.  We need something where we can get lots of info on the home page but it still looks clean.

**Comment by rkalnins** [comment]
A lot of schools have really messy home pages...PPS actually has one of the better websites I've seen in terms of design (it's just better than the others).  Lots of info but clean.

**Comment by rkalnins** [comment]
I like the what we have right now.  There's lots of menu space and it should be easy to get all of the important information were it needs to go.

**Comment by sidpagariya** [comment]
Did you already pull the other branch and run it? I think that would work out, too...

**Comment by rkalnins** [comment]
I pulled the one new look and feel. I'll pull the other.
